language: ruby
rvm:
- 2.2.0
sudo: false
sscript: bundle exec jekyll build && bundle exec rake deploy 
addons:
  apt:
    packages:
    - graphviz 
env:
  global:
    secure: pvhbwmy3cStLScRmOoK9U/uZzEYqni3pEf6Wlw15Ini8cEAP86aTnh8J/Hl4ID/ZoqsmbqlqJe/ZyxQN4U3gkRhT/j3XU3Z84cgtccxe6t8vQikbHajGlUyVgnNhv/VX8/PppilXnJuqmhZqDZVNAZFM00bXe1ftpBs46ZZY0L9uM9NE3PguaYYx/iIwgV42lf4yN27ZcdGwKQSeAvS1G+nn77kj5a4xmIeTipreCV7CkPDgrigpjBY7IRx5Omjulo5C6e5Ekgmzrna90twQ91ULFbwcdxnkEdkuHz1S44R7XdkaO/8rxCnXFxVM40KbGj/pipj8CHiIiQ5LvnYV6xx/boubC0BKWf5/Irpti8RYjPzZDWFMfeyW9xYEHS46N6ZUDX6InTCWQfNpeqKTLFTCR3Z6GxolYSu5abFv7xOiepF1lGL+VBef0x8pB9YD/SvzuyVX2TdNUznj/fO2Ydbfhp72aS2TwdixhRx495DZ5/6SpwF+opjTpJSNIrQOtFJKgdil+s4Y6JsKv6f7v7rxW3mfVdJeHQahjutIJxVp+8LgVk5u3X4jvOdC0KcdxSE6KT/3oSdzYPDLHHHCspb+m+5UItmaSOMtj9sqZkkKovZf2lMWJrI3r9kcHwdPTakyqR1gNpfEGsoUfEev2/NRnX8J/wWqV+5WFDASlbs=
